language: python

python:
  - "3.4"
  - "2.7"

branches:
  only:
    - master

before_install:
  - pip install -U pip

install:
  - pip install -r requirements.txt
  - python setup.py install
  - pip install -r requirements-dev.txt

before_script:
  - cd tests
  - export DJANGO_SETTINGS_MODULE=tests.settings

script:
  - python manage.py test

after_success:
  coveralls